modLoader="javafml"
loaderVersion="[47,)"
issueTrackerURL="https://github.com/MC-U-Team/Useful-Dragon-Eggs/issues"
license="Apache-2.0 License"

[[mods]]
	modId="usefuldragoneggs"
	version="${file.jarVersion}"
	displayName="Useful Dragon Eggs"
	displayURL="https://u-team.info/mods/usefuldragoneggs"
	updateJSONURL="https://api.u-team.info/update/usefuldragoneggs.json"
	logoFile="logo.png"
	credits="Team U-Team"
	authors="HyCraftHD"
	description="Join our discord server here: https://discord.hycrafthd.net\n\nThis mod adds a command to give dragon eggs a use. The command can revert MC-94186 / MC-122524 to give the dragon egg the possibility to break bedrock again."
	
	[[dependencies.usefuldragoneggs]]
	    modId="forge"
	    mandatory=true
	    versionRange="[47.0.35,)"
	    ordering="NONE"
	    side="BOTH"
	
	[[dependencies.usefuldragoneggs]]
	    modId="minecraft"
	    mandatory=true
	    versionRange="[1.20.1]"
	    ordering="NONE"
	    side="BOTH"
	    
	[[dependencies.usefuldragoneggs]]
	    modId="uteamcore"
	    mandatory=true
	    versionRange="[5.1.3.268,)"
	    ordering="NONE"
	    side="BOTH"